import { expect, test } from '@playwright/test';
import { makeIPK } from '../adapters/fixtures';
import { loginAdmin } from './support';

test('管理员投稿也要打开审核收件箱，先查看版本再通过上架',async({page,request})=>{
  await loginAdmin(page);
  const bytes=Buffer.from(await makeIPK());
  const response=await page.request.post('/api/studio/submit/upload',{headers:{Origin:'http://127.0.0.1:8789'},multipart:{name:'管理员待审样例',description:'验证管理员提交同样需要人工审核',tutorial:'# 安装说明\n安装后启用。',file:{name:'manual-demo.ipk',mimeType:'application/octet-stream',buffer:bytes}}});
  expect(response.status()).toBe(202); const {pluginId}=await response.json();
  await expect.poll(async()=> (await (await page.request.get(`/api/studio/plugins/${pluginId}`)).json()).candidate?.decision).toBe('pending');
  expect((await request.get(`/api/plugins/${pluginId}`)).status()).toBe(404);
  expect((await request.get(`/api/plugins/${pluginId}/download/1`)).status()).toBe(404);
  await page.getByLabel('搜索待审作品').fill('管理员待审样例');
  await expect(page.locator('.review-item')).toHaveCount(1);
  await page.getByRole('button',{name:'开始审核',exact:true}).click();
  const drawer=page.getByRole('dialog',{name:'管理员待审样例',exact:true});
  await expect(drawer).toContainText('安装说明');
  await expect(drawer).toContainText('manual-demo.ipk');
  const downloadWait=page.waitForEvent('download');
  await drawer.getByRole('link',{name:'下载检查',exact:true}).click();
  const file=await downloadWait; expect(file.suggestedFilename()).toBe('manual-demo.ipk');
  await page.screenshot({path:test.info().outputPath('manual-review-drawer-1280.png'),fullPage:true});
  await drawer.getByRole('button',{name:'通过并上架',exact:true}).click();
  await expect(drawer).not.toBeVisible();
  expect((await request.get(`/api/plugins/${pluginId}`)).status()).toBe(200);
  await page.goto(`/plugins/${pluginId}`);
  await page.getByRole('tab',{name:'审核信息',exact:true}).click();
  await expect(page.getByText('人工审核通过',{exact:true})).toBeVisible();
  const info=await (await request.get('/__test/info')).json(); expect(info.aiCalls).toBe(0); expect(info.scanCalls).toBe(0);
});

test('退回反馈必填、不会上架，窄屏审核抽屉可操作',async({page,request})=>{
  await page.setViewportSize({width:375,height:812}); await loginAdmin(page);
  const response=await page.request.post('/api/studio/submit/upload',{headers:{Origin:'http://127.0.0.1:8789'},multipart:{name:'待补充资料样例',description:'缺少设备支持说明',tutorial:'# 使用说明\n<script>window.__reviewExecuted=true</script>\n[危险](javascript:alert(1))',file:{name:'returned.ipk',mimeType:'application/octet-stream',buffer:Buffer.from(await makeIPK())}}});
  const {pluginId}=await response.json();
  await expect.poll(async()=> (await (await page.request.get(`/api/studio/plugins/${pluginId}`)).json()).candidate?.decision).toBe('pending');
  await page.getByLabel('搜索待审作品').fill('待补充资料样例');
  await page.getByRole('button',{name:'开始审核',exact:true}).click();
  const drawer=page.getByRole('dialog',{name:'待补充资料样例',exact:true});
  await expect(drawer.locator('.review-readme script,.review-readme a[href^="javascript:"]')).toHaveCount(0);
  await drawer.getByRole('button',{name:'退回修改',exact:true}).click();
  await expect(drawer.getByRole('alert')).toContainText('至少 5 字');
  await drawer.getByLabel('给作者的反馈').fill('请补充支持的路由器型号及卸载方法');
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
  const box=await drawer.boundingBox(); expect(box?.y).toBe(0); expect((box?.y||0)+(box?.height||0)).toBeLessThanOrEqual(812);
  await page.screenshot({path:test.info().outputPath('manual-review-drawer-375.png')});
  await drawer.getByRole('button',{name:'退回修改',exact:true}).click();
  await expect(drawer).not.toBeVisible();
  expect((await request.get(`/api/plugins/${pluginId}`)).status()).toBe(404);
  await page.getByRole('button',{name:'已退回',exact:true}).click();
  await expect(page.locator('.review-item')).toContainText('请补充支持的路由器型号及卸载方法');
});
