PRAGMA foreign_keys=ON;
CREATE TABLE users(id TEXT PRIMARY KEY, phone_index TEXT NOT NULL UNIQUE, phone_mask TEXT NOT NULL, created_at INTEGER NOT NULL);
CREATE TABLE admins(id TEXT PRIMARY KEY, username TEXT NOT NULL UNIQUE COLLATE NOCASE, password_hash TEXT NOT NULL, created_at INTEGER NOT NULL, updated_at INTEGER NOT NULL);
CREATE TABLE sessions(token_hash TEXT PRIMARY KEY,kind TEXT NOT NULL CHECK(kind IN ('user','admin')),subject_id TEXT NOT NULL,expires_at INTEGER NOT NULL);
CREATE INDEX sessions_expiry ON sessions(expires_at);
CREATE TABLE plugins(id TEXT PRIMARY KEY,repository_id INTEGER NOT NULL UNIQUE,full_name TEXT NOT NULL,submitter_id TEXT REFERENCES users(id),status TEXT NOT NULL DEFAULT 'pending',blocked INTEGER NOT NULL DEFAULT 0,revision INTEGER NOT NULL DEFAULT 1,approved_snapshot_id TEXT,description TEXT NOT NULL DEFAULT '',public_reason TEXT NOT NULL DEFAULT '等待自动检查',created_at INTEGER NOT NULL,updated_at INTEGER NOT NULL,checked_at INTEGER,missing_since INTEGER,missing_count INTEGER NOT NULL DEFAULT 0,download_count INTEGER NOT NULL DEFAULT 0);
CREATE INDEX plugins_market ON plugins(status,updated_at DESC,id);
CREATE INDEX plugins_submitter ON plugins(submitter_id);
CREATE TABLE snapshots(id TEXT PRIMARY KEY,plugin_id TEXT NOT NULL REFERENCES plugins(id),revision INTEGER NOT NULL,fingerprint TEXT NOT NULL,data TEXT NOT NULL,verdict TEXT NOT NULL,public_reason TEXT NOT NULL,internal_reason TEXT NOT NULL,review_version TEXT NOT NULL,created_at INTEGER NOT NULL,UNIQUE(plugin_id,fingerprint,review_version));
CREATE TABLE assets(id INTEGER NOT NULL,snapshot_id TEXT NOT NULL REFERENCES snapshots(id),plugin_id TEXT NOT NULL REFERENCES plugins(id),name TEXT NOT NULL,size INTEGER NOT NULL,sha256 TEXT NOT NULL,data TEXT NOT NULL,disabled INTEGER NOT NULL DEFAULT 0,PRIMARY KEY(snapshot_id,id));
CREATE TABLE tasks(id TEXT PRIMARY KEY,plugin_id TEXT NOT NULL REFERENCES plugins(id),revision INTEGER NOT NULL,status TEXT NOT NULL,force_review INTEGER NOT NULL DEFAULT 0,attempts INTEGER NOT NULL DEFAULT 0,lock_until INTEGER,lock_token TEXT,not_before INTEGER NOT NULL DEFAULT 0,queued_at INTEGER,public_reason TEXT NOT NULL DEFAULT '',internal_reason TEXT NOT NULL DEFAULT '',created_at INTEGER NOT NULL,updated_at INTEGER NOT NULL,UNIQUE(plugin_id,revision));
CREATE INDEX tasks_recovery ON tasks(status,not_before,lock_until);
CREATE TABLE favorites(user_id TEXT NOT NULL REFERENCES users(id),plugin_id TEXT NOT NULL REFERENCES plugins(id),created_at INTEGER NOT NULL,PRIMARY KEY(user_id,plugin_id));
CREATE INDEX favorites_plugin ON favorites(plugin_id);
CREATE TABLE download_attempts(identity TEXT NOT NULL,plugin_id TEXT NOT NULL,asset_id INTEGER NOT NULL,bucket INTEGER NOT NULL,created_at INTEGER NOT NULL,PRIMARY KEY(identity,plugin_id,asset_id,bucket));
CREATE TABLE settings(key TEXT PRIMARY KEY,value TEXT NOT NULL);
CREATE TABLE audit(id TEXT PRIMARY KEY,admin_id TEXT,action TEXT NOT NULL,target TEXT NOT NULL,created_at INTEGER NOT NULL);
CREATE TABLE limits(key TEXT PRIMARY KEY,count INTEGER NOT NULL,expires_at INTEGER NOT NULL);
CREATE TABLE ai_usage(day TEXT PRIMARY KEY,count INTEGER NOT NULL DEFAULT 0);
CREATE TABLE http_cache(key TEXT PRIMARY KEY,etag TEXT,value TEXT NOT NULL,updated_at INTEGER NOT NULL);
CREATE TRIGGER admin_password_changed AFTER UPDATE OF password_hash ON admins WHEN OLD.password_hash<>NEW.password_hash BEGIN DELETE FROM sessions WHERE kind='admin' AND subject_id=NEW.id; END;
