import { env as bindings } from 'cloudflare:workers';
import { createExecutionContext } from 'cloudflare:test';
import { describe, it, expect, vi } from 'vitest';
import worker from '../../worker/index';
import { type Env, AppError } from '../../worker/contracts';
import { processTask, submit, refresh, recover } from '../../worker/pipeline';
import { createSession } from '../../worker/security';
import { saveAI } from '../../worker/settings';
import { makeGitHubFixture } from '../adapters/fixtures';

const env=()=>({...bindings,JOBS:{send:vi.fn(async()=>undefined)}} as unknown as Env);
const origin='https://store.example.com';
function request(e:Env,path:string,method='GET',body?:unknown,cookie?:string,headers:Record<string,string>={}){return worker.fetch(new Request(origin+path,{method,headers:{...(method==='GET'||method==='HEAD'?{}:{Origin:origin,'Content-Type':'application/json'}),...(cookie?{Cookie:cookie}:{}),...headers},...(body===undefined?{}:{body:JSON.stringify(body)})}),e,createExecutionContext());}
async function setup(options:{ai?:'allow'|'reject'|'uncertain'|'invalid';callback?:()=>Promise<void>}={}){const e=env();const fixture=await makeGitHubFixture();const aiCalls:Record<string,unknown>[]=[];
vi.spyOn(globalThis,'fetch').mockImplementation(async(input,init)=>{const url=String(input);if(url.startsWith('https://ai.vendor.com/')){aiCalls.push(JSON.parse(String(init?.body)));await options.callback?.();return Response.json({choices:[{finish_reason:'stop',message:{content:options.ai==='invalid'?'not JSON':JSON.stringify({verdict:options.ai??'allow',publicReason:'隔离测试：静态材料符合预期',internalReason:'仅fixture模型响应；实际扫描包含源码、控制与安装脚本'})}}]});}return fixture.fetcher(input,init);});
if(options.ai)await saveAI(e,{baseUrl:'https://ai.vendor.com/v1',model:'fixture-model',apiKey:'isolated-key',timeoutMs:1000,maxRetries:0,inputBudget:100000,outputBudget:1500,rules:'fixture rule',structuredOutput:false});
return {e,fixture,aiCalls};}
async function publish(){const x=await setup({ai:'allow'});const task=await submit(x.e,'https://github.com/fixture/harmless',null);await processTask(x.e,task.taskId!);return {...x,task};}
async function adminCookie(e:Env){await e.DB.prepare("INSERT INTO admins VALUES('admin','fixture-admin','unused',?,?)").bind(Date.now(),Date.now()).run();return (await createSession(e,'admin','admin')).cookie.split(';')[0]!;}

describe('实际 Workers/D1 API 与持久审核流程',()=>{
it('游客仅可浏览；写入要求会话与来源，普通用户不能调用Studio',async()=>{const e=env();expect((await request(e,'/api/plugins')).status).toBe(200);expect((await request(e,'/api/submit','POST',{url:'https://github.com/a/b'})).status).toBe(401);expect((await request(e,'/api/studio/tasks')).status).toBe(401);expect((await request(e,'/api/login','POST',{phone:'13800138000'},undefined,{Origin:'https://evil.com'})).status).toBe(403);
const login=await request(e,'/api/login','POST',{phone:'13800138000'});expect(login.status).toBe(200);const cookie=login.headers.get('set-cookie')!.split(';')[0]!;expect(login.headers.get('set-cookie')).toContain('HttpOnly');expect((await request(e,'/api/studio/ai','GET',undefined,cookie)).status).toBe(401);const user=await e.DB.prepare('SELECT * FROM users').first();expect(JSON.stringify(user)).not.toContain('13800138000');expect(JSON.stringify(user)).not.toContain('+8613800138000');expect((await request(e,'/api/logout','POST',{},cookie)).status).toBe(200);expect((await request(e,'/api/me','GET',undefined,cookie)).status).toBe(401);});
it('真实仓库源码与IPK解析、严格AI结果、原子自动上架，重复投稿和任务不重复AI',async()=>{const x=await publish();const row=await x.e.DB.prepare('SELECT * FROM plugins').first();expect(row?.status).toBe('published');expect(x.aiCalls).toHaveLength(1);expect(JSON.stringify(x.aiCalls[0])).toContain('postinst');expect(JSON.stringify(x.aiCalls[0])).toContain('src/harmless.sh');expect(JSON.stringify(x.aiCalls[0])).not.toContain('PHONE_HMAC_KEY');const detail=await (await request(x.e,`/api/plugins/${x.task.pluginId}`)).json() as any;expect(detail.readme).toBe(x.fixture.readme);expect(detail.sourceCommit).not.toBe(detail.readmeCommit);expect(detail.assets[0].sha256).toBe(x.fixture.asset.digest.slice(7));expect((await request(x.e,'/api/plugins')).headers.get('cache-control')).toBe('no-store');
await processTask(x.e,x.task.taskId!);const duplicate=await submit(x.e,'https://github.com/fixture/harmless.git',null);expect(duplicate.pluginId).toBe(x.task.pluginId);expect(duplicate.taskId).toBeNull();expect(x.aiCalls).toHaveLength(1);
const again=await refresh(x.e,x.task.pluginId!);await processTask(x.e,again.taskId);expect(x.aiCalls).toHaveLength(1);const after=await x.e.DB.prepare('SELECT updated_at FROM plugins').first();expect(after?.updated_at).toBe(row?.updated_at);});
it('缺少AI配置不得默认放行，持久任务保留等待配置状态',async()=>{const x=await setup();const task=await submit(x.e,'https://github.com/fixture/harmless',null);await processTask(x.e,task.taskId!);expect((await x.e.DB.prepare('SELECT status FROM tasks').first())?.status).toBe('waiting_config');expect((await request(x.e,'/api/plugins')).status).toBe(200);expect(((await (await request(x.e,'/api/plugins')).json()) as any).total).toBe(0);expect(x.aiCalls).toHaveLength(0);});
it.each(['reject','uncertain','invalid'] as const)('AI %s不会上架',async(ai)=>{const x=await setup({ai});const task=await submit(x.e,'https://github.com/fixture/harmless',null);await processTask(x.e,task.taskId!).catch(()=>undefined);const p=await x.e.DB.prepare('SELECT approved_snapshot_id FROM plugins').first();expect(p?.approved_snapshot_id).toBeNull();expect(x.aiCalls).toHaveLength(1);});
it('无正式Release/IPK区分等待发布包，仓库不被误标删除',async()=>{const x=await setup({ai:'allow'});x.fixture.paths.set('/repos/fixture/harmless/releases/latest',new Response(null,{status:404}));const task=await submit(x.e,'https://github.com/fixture/harmless',null);await processTask(x.e,task.taskId!);expect((await x.e.DB.prepare('SELECT status FROM tasks').first())?.status).toBe('waiting_package');expect((await x.e.DB.prepare('SELECT missing_count FROM plugins').first())?.missing_count).toBe(0);expect(x.aiCalls).toHaveLength(0);});
it('tag在审核期间移动时不发布旧材料',async()=>{const x=await setup({ai:'allow'});const original=vi.mocked(globalThis.fetch).getMockImplementation()!;vi.spyOn(globalThis,'fetch').mockImplementation(async(input,init)=>{if(String(input).startsWith('https://ai.vendor.com/'))x.fixture.paths.set('/repos/fixture/harmless/git/ref/tags/v1.0.0',{object:{type:'commit',sha:'d'.repeat(40)}});return original(input,init);});const task=await submit(x.e,'https://github.com/fixture/harmless',null);await processTask(x.e,task.taskId!);expect((await x.e.DB.prepare('SELECT approved_snapshot_id FROM plugins').first())?.approved_snapshot_id).toBeNull();expect((await x.e.DB.prepare('SELECT status FROM tasks').first())?.status).toBe('incomplete');});
it('审核期间管理员删除，迟到allow与下一次同步无法复活',async()=>{const x=await setup({ai:'allow'});const task=await submit(x.e,'https://github.com/fixture/harmless',null);const cookie=await adminCookie(x.e);const original=vi.mocked(globalThis.fetch).getMockImplementation()!;vi.spyOn(globalThis,'fetch').mockImplementation(async(input,init)=>{if(String(input).startsWith('https://ai.vendor.com/'))expect((await request(x.e,`/api/studio/plugins/${task.pluginId}/delete`,'POST',{reason:'测试停用'},cookie)).status).toBe(200);return original(input,init);});await processTask(x.e,task.taskId!);expect((await x.e.DB.prepare('SELECT blocked FROM plugins').first())?.blocked).toBe(1);expect((await request(x.e,`/api/plugins/${task.pluginId}`)).status).toBe(404);await expect(refresh(x.e,task.pluginId!)).rejects.toBeInstanceOf(AppError);await processTask(x.e,task.taskId!);expect((await x.e.DB.prepare('SELECT status FROM plugins').first())?.status).toBe('removed');expect((await x.e.DB.prepare('SELECT COUNT(*) n FROM snapshots').first())?.n).toBe(0);expect((await x.e.DB.prepare('SELECT COUNT(*) n FROM assets').first())?.n).toBe(0);expect((await x.e.DB.prepare('SELECT COUNT(*) n FROM http_cache').first())?.n).toBe(0);});
it('未审新版本不公开，旧批准版本继续展示实际版本',async()=>{const x=await publish();x.fixture.release.id=3002;x.fixture.release.tag_name='v2.0.0';x.fixture.paths.set('/repos/fixture/harmless/git/ref/tags/v2.0.0',{object:{type:'commit',sha:x.fixture.sourceCommit}});x.fixture.paths.set('/repos/fixture/harmless/releases/3002',x.fixture.release);x.fixture.paths.set('/repos/fixture/harmless/releases/3002/assets?per_page=100&page=1',[]);const next=await refresh(x.e,x.task.pluginId!);await processTask(x.e,next.taskId);const detail=await (await request(x.e,`/api/plugins/${x.task.pluginId}`)).json() as any;expect(detail.plugin.version).toBe('v1.0.0');expect((await x.e.DB.prepare('SELECT status FROM tasks WHERE id=?').bind(next.taskId).first())?.status).toBe('waiting_package');});
it('出站队列故障后任务持久保存且可恢复入队，重复投稿并发只创建一个插件',async()=>{const x=await setup();let reject=true;(x.e.JOBS.send as any).mockImplementation(async()=>{if(reject)throw new Error('queue unavailable');});const submitted=await Promise.all([submit(x.e,'https://github.com/fixture/harmless',null),submit(x.e,'https://github.com/fixture/harmless',null)]);expect(new Set(submitted.map(s=>s.pluginId)).size).toBe(1);expect((await x.e.DB.prepare('SELECT COUNT(*) n FROM tasks').first())?.n).toBe(1);expect((await x.e.DB.prepare('SELECT queued_at FROM tasks').first())?.queued_at).toBeNull();reject=false;await recover(x.e);expect((await x.e.DB.prepare('SELECT queued_at FROM tasks').first())?.queued_at).toBeGreaterThan(0);});
it('并发重复收藏/取消幂等，计数不可被客户端直接写入',async()=>{const x=await publish();const login=await request(x.e,'/api/login','POST',{phone:'13800138000'});const cookie=login.headers.get('set-cookie')!.split(';')[0]!;await Promise.all(Array.from({length:8},()=>request(x.e,`/api/plugins/${x.task.pluginId}/favorite`,'PUT',{active:true,count:999},cookie)));let detail=await (await request(x.e,`/api/plugins/${x.task.pluginId}`,'GET',undefined,cookie)).json() as any;expect(detail.plugin.favorite_count).toBe(1);expect(detail.plugin.favorited).toBe(true);const list=await (await request(x.e,'/api/plugins','GET',undefined,cookie)).json() as any;expect(list.items[0].favorited).toBe(true);await Promise.all(Array.from({length:8},()=>request(x.e,`/api/plugins/${x.task.pluginId}/favorite`,'PUT',{active:false},cookie)));detail=await (await request(x.e,`/api/plugins/${x.task.pluginId}`)).json() as any;expect(detail.plugin.favorite_count).toBe(0);});
it('一次404/临时403不误删；两次跨小时官方不可访问才公开移除',async()=>{const x=await publish();x.fixture.paths.set('/repositories/1001',new Response(null,{status:404}));let next=await refresh(x.e,x.task.pluginId!);await processTask(x.e,next.taskId);expect((await x.e.DB.prepare('SELECT status FROM plugins').first())?.status).toBe('published');await x.e.DB.prepare('UPDATE plugins SET missing_since=?').bind(Date.now()-3600001).run();next=await refresh(x.e,x.task.pluginId!);await processTask(x.e,next.taskId);expect((await x.e.DB.prepare('SELECT status FROM plugins').first())?.status).toBe('removed');expect((await request(x.e,`/api/plugins/${x.task.pluginId}`)).status).toBe(404);});
it('管理员显式重审调用AI，配置读取只返回掩码且普通会话不可读',async()=>{const x=await publish();const cookie=await adminCookie(x.e);const masked=await (await request(x.e,'/api/studio/ai','GET',undefined,cookie)).json() as any;expect(masked.apiKey).toBe('••••••••');expect(JSON.stringify(await x.e.DB.prepare("SELECT value FROM settings WHERE key='ai'").first())).not.toContain('isolated-key');const response=await request(x.e,`/api/studio/plugins/${x.task.pluginId}/retry`,'POST',{},cookie);expect(response.status).toBe(200);const task=await response.json() as any;await processTask(x.e,task.taskId);expect(x.aiCalls).toHaveLength(2);});
it('每日审核预算耗尽后停止调用AI，生产缺配置也没有mock开关',async()=>{const x=await setup({ai:'allow'});x.e.DAILY_AI_BUDGET='1';const task=await submit(x.e,'https://github.com/fixture/harmless',null);await processTask(x.e,task.taskId!);const next=await refresh(x.e,task.pluginId!,true);await processTask(x.e,next.taskId);expect(x.aiCalls).toHaveLength(1);expect((await x.e.DB.prepare('SELECT status FROM tasks WHERE id=?').bind(next.taskId).first())?.status).toBe('budget_exhausted');const response=await request({...x.e,APP_ENV:'production',MASTER_KEY:''},'/api/plugins');expect(response.status).toBe(503);});
});

it('删除已发布插件清除材料、收藏及下载记录，个人提交保留最小下架状态',async()=>{
const x=await publish();const cookie=await adminCookie(x.e);
const login=await request(x.e,'/api/login','POST',{phone:'13800138000'});const userCookie=login.headers.get('set-cookie')!.split(';')[0]!;
await x.e.DB.prepare('UPDATE plugins SET submitter_id=(SELECT id FROM users LIMIT 1)').run();
await request(x.e,`/api/plugins/${x.task.pluginId}/favorite`,'PUT',{active:true},userCookie);
expect((await request(x.e,`/api/studio/plugins/${x.task.pluginId}/delete`,'POST',{reason:'已下架'},cookie)).status).toBe(200);
for(const table of ['snapshots','assets','http_cache','favorites','download_attempts'])expect((await x.e.DB.prepare(`SELECT COUNT(*) n FROM ${table}`).first())?.n).toBe(0);
const me=await (await request(x.e,'/api/me','GET',undefined,userCookie)).json() as any;expect(me.submissions[0].status).toBe('removed');expect(me.submissions[0].public_reason).toBe('已下架');expect(me.favorites).toHaveLength(0);
const duplicate=await submit(x.e,'https://github.com/fixture/harmless',null);expect(duplicate.taskId).toBeNull();expect(duplicate.status).toBe('removed');expect((await x.e.DB.prepare('SELECT COUNT(*) n FROM http_cache').first())?.n).toBe(0);
});
