import { env as bindings } from 'cloudflare:workers';
import { describe,it,expect,vi } from 'vitest';
import worker from '../../worker/index';
import { type Env } from '../../worker/contracts';
import { processTask,submit,refresh } from '../../worker/pipeline';
import { saveAI } from '../../worker/settings';
import { makeGitHubFixture } from '../adapters/fixtures';
const config={baseUrl:'https://ai.vendor.com/v1',model:'fixture',apiKey:'fixture-key',timeoutMs:1000,maxRetries:0,inputBudget:100000,outputBudget:1500,rules:'fixture',structuredOutput:false};
async function setup(){const env={...bindings,JOBS:{send:vi.fn(async()=>undefined)}} as unknown as Env;const fixture=await makeGitHubFixture();let aiCalls=0;vi.spyOn(globalThis,'fetch').mockImplementation(async(input,init)=>{if(String(input).startsWith('https://ai.vendor.com')){aiCalls++;return Response.json({choices:[{finish_reason:'stop',message:{content:JSON.stringify({verdict:'allow',publicReason:'隔离样例通过',internalReason:'测试内部依据'})}}]});}return fixture.fetcher(input,init);});await saveAI(env,config);return{env,fixture,aiCalls:()=>aiCalls};}
describe('队列租约、恢复与发布竞态回归',()=>{
it('审核中修改配置会重新排队，不能显示虚假的已完成发布',async()=>{const x=await setup();const task=await submit(x.env,'https://github.com/fixture/harmless',null);const old=vi.mocked(fetch).getMockImplementation()!;let changed=false;vi.spyOn(globalThis,'fetch').mockImplementation(async(input,init)=>{if(!changed&&String(input).startsWith('https://ai.vendor.com')){changed=true;await saveAI(x.env,{...config,rules:'new-rules'});}return old(input,init);});await processTask(x.env,task.taskId!);expect((await x.env.DB.prepare('SELECT approved_snapshot_id FROM plugins').first())?.approved_snapshot_id).toBeNull();expect((await x.env.DB.prepare('SELECT status FROM tasks').first())?.status).toBe('retry');await processTask(x.env,task.taskId!);expect((await x.env.DB.prepare('SELECT status FROM plugins').first())?.status).toBe('published');expect(x.aiCalls()).toBe(2);});
it('并发重复队列只允许一个租约和一个AI调用；旧revision任务失效',async()=>{const x=await setup();const task=await submit(x.env,'https://github.com/fixture/harmless',null);await Promise.all([processTask(x.env,task.taskId!),processTask(x.env,task.taskId!)]);expect(x.aiCalls()).toBe(1);const first=await refresh(x.env,task.pluginId!,true);const second=await refresh(x.env,task.pluginId!,true);await processTask(x.env,second.taskId);await processTask(x.env,first.taskId);expect((await x.env.DB.prepare('SELECT status FROM tasks WHERE id=?').bind(first.taskId).first())?.status).toBe('superseded');expect(x.aiCalls()).toBe(2);});
it('根仓库曾恢复公开而材料不足，会清除疑似删除累计',async()=>{const x=await setup();const task=await submit(x.env,'https://github.com/fixture/harmless',null);await processTask(x.env,task.taskId!);await x.env.DB.prepare('UPDATE plugins SET missing_count=1,missing_since=?').bind(Date.now()-7200000).run();x.fixture.paths.set('/repos/fixture/harmless/releases/latest',new Response(null,{status:404}));const next=await refresh(x.env,task.pluginId!);await processTask(x.env,next.taskId);expect((await x.env.DB.prepare('SELECT missing_count FROM plugins').first())?.missing_count).toBe(0);x.fixture.paths.set('/repositories/1001',new Response(null,{status:404}));const missing=await refresh(x.env,task.pluginId!);await processTask(x.env,missing.taskId);expect((await x.env.DB.prepare('SELECT status FROM plugins').first())?.status).toBe('published');});
it('Cron分批启动检查并清理过期会话；失败任务有有限重试与死信状态',async()=>{const x=await setup();const task=await submit(x.env,'https://github.com/fixture/harmless',null);await x.env.DB.prepare("INSERT INTO sessions VALUES('expired','user','someone',0)").run();await worker.scheduled({cron:'0 4,16 * * *'} as ScheduledController,x.env);expect((await x.env.DB.prepare('SELECT COUNT(*) n FROM sessions').first())?.n).toBe(0);expect(x.env.JOBS.send).toHaveBeenCalled();
x.fixture.paths.set('/repositories/1001',new Response(null,{status:503}));for(let attempt=0;attempt<4;attempt++){await x.env.DB.prepare('UPDATE tasks SET not_before=0 WHERE id=?').bind(task.taskId).run();await processTask(x.env,task.taskId!).catch(()=>undefined);}expect((await x.env.DB.prepare('SELECT status FROM tasks WHERE id=?').bind(task.taskId).first())?.status).toBe('failed');const calls=x.fixture.calls.length;await processTask(x.env,task.taskId!);expect(x.fixture.calls.length).toBe(calls);expect((await x.env.DB.prepare('SELECT status FROM plugins').first())?.status).not.toBe('removed');});
it('过期执行锁可恢复；队列ack与retry行为可执行',async()=>{const x=await setup();const task=await submit(x.env,'https://github.com/fixture/harmless',null);await x.env.DB.prepare("UPDATE tasks SET status='running',lock_until=0,lock_token='crashed',attempts=1 WHERE id=?").bind(task.taskId).run();const ack=vi.fn(),retry=vi.fn();await worker.queue({messages:[{body:{taskId:task.taskId!},ack,retry}]} as unknown as MessageBatch<{taskId?:string;scanCursor?:string}>,x.env);expect(ack).toHaveBeenCalledOnce();expect(retry).not.toHaveBeenCalled();expect((await x.env.DB.prepare('SELECT status FROM plugins').first())?.status).toBe('published');});
});
